apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-init
  name: test-init
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    args: 
    - sleep infinity
    image: quay.io/quay/busybox
    name: busybox
  initContainers: # initContainer 的列表，下边可写的字段和 containers 的一样
  - command: 
    - /bin/sh
    - -c
    args: 
    - |
      echo "Check DNS..."
      nc -vz kubernetes.default 443
      if [ $? != 0 ] ; then
      exit 1
      fi
    image: quay.io/quay/busybox
    name: busybox-init
