apiVersion: v1
kind: Service
metadata:
  labels:
    app: statefulset-service-demo
  name: statefulset-service-demo
spec:
  clusterIP: None
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: statefulset-demo
  type: ClusterIP
