apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: quay.io/prometheus/busybox
        command:
        - sh
        - -c
        - |
          echo "Hello Kubernetes Job"
          sleep 5
          echo "Job Finished"
