apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-demo
  name: service-demo
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: service-demo
  type: NodePort
status:
  loadBalancer: {}
