apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-demo
  name: service-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-demo
    spec:
      containers:
      - image: quay.io/nginx/nginx-unprivileged
        name: nginx-unprivileged
        resources: {}
status: {}
